Models/CuisineType.cs
namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        German,
        Serbian
    }
}

Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Binders;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name = "Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

ViewModels/RestaurantEditModel.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;

namespace OdeToFood.ViewModels
{
    [ModelMetadataType(typeof(Restaurant))]
    public class RestaurantEditModel
    {
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            var redirectUrl = Url.Page("/Index");
            return Challenge(
                new AuthenticationProperties { RedirectUri = redirectUrl },
                // challenge the user by logging in with OIDC server
                OpenIdConnectDefaults.AuthenticationScheme
            );
        }

        public IActionResult Logout()
        {
            var callbackUrl = Url.Page("/Account/SignedOut");
            return SignOut(
                new AuthenticationProperties { RedirectUri = callbackUrl },
                // remove cookie that authenticates user
                CookieAuthenticationDefaults.AuthenticationScheme, 
                // also logout of OIDC identity provider
                OpenIdConnectDefaults.AuthenticationScheme
            );
        }
    }
}

Pages/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Account
{
    public class SignedOutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;
        private readonly IGreeter _greeter;

        public IndexModel(IRestaurantData restaurantData, IGreeter greeter)
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        public IEnumerable<Restaurant> Restaurants => _restaurantData.GetAll();
        public String CurrentMessage => _greeter.GetMessageOfTheDay();

        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

Pages/Restaurants/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Binders;
using OdeToFood.Extensions;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.Utils;
using OdeToFood.ViewModels;

namespace OdeToFood.Pages.Restaurants
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        public CreateModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        [BindProperty]
        public RestaurantEditModel Restaurant { get; set; }
        public IEnumerable<SelectListItem> CuisineTypes => EnumUtils.ToSelectListItems<CuisineType>();

        public IActionResult OnGet()
        {
            return Page();
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var newRestaurant = new Restaurant
            {
                Name = Restaurant.Name,
                Cuisine = Restaurant.Cuisine
            };
            newRestaurant = _restaurantData.Add(newRestaurant);

            return RedirectToPage(nameof(DetailsModel).ToPageName(), new { id = newRestaurant.Id });
        }
    }
}

Pages/Restaurants/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Binders;
using OdeToFood.Extensions;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    public class DetailsModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        public DetailsModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public Restaurant Restaurant { get; private set; }

        public IActionResult OnGet([ModelBinder(Name = "id", BinderType = typeof(RestaurantBinder))]
                                   Restaurant restaurant)
        {
            if (restaurant == null)
            {
                return RedirectToPage($"/{nameof(IndexModel).ToPageName()}");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToPage($"/{nameof(IndexModel).ToPageName()}");
            }

            Restaurant = restaurant;
            return Page();
        }
    }
}

Pages/Restaurants/Edit.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Extensions;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.Utils;

namespace OdeToFood.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> CuisineTypes => EnumUtils.ToSelectListItems<CuisineType>();

        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);

            if (Restaurant == null)
            {
                return RedirectToPage(nameof(IndexModel).ToPageName());
            }

            return Page();
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Restaurant = _restaurantData.Update(Restaurant);
                return RedirectToPage(nameof(DetailsModel).ToPageName(), new { id = Restaurant.Id });
            }
            return Page();
        }
    }
}

ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private readonly IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;    
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();
            return View("Default", model);
        }
    }
}

ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Pages/Account/SignedOut.cshtml
@page

<div>You are signed out.</div>
<a asp-page="/Index">Go Home</a>

Pages/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

Pages/Components/LoginLogout/Default.cshtml
@if(User.Identity.IsAuthenticated)
{
    <div>Hello, @User.Identity.Name</div>
    <a class="btn btn-default" asp-controller="Account" asp-action="Logout">Logout</a>
}
else
{
    <a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>All Restaurants</h1>

@foreach (var restaurant in @Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)
}

<div>
    <a class="btn btn-primary" asp-page="/Restaurants/Create">Add Restaurant</a>
</div>

Pages/Restaurants/Create.cshtml
@page
@model CreateModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post">
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>
    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine" asp-items="Model.CuisineTypes"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <input type="submit" name"save" value="Save" />
</form>
<div>
    <a asp-page="/Index">Home</a>
</div>

Pages/Restaurants/Details.cshtml
@page "{id:int?}"
@model DetailsModel
@{
    ViewData["Title"] = Model.Restaurant.Name;
}

<h1>@Model.Restaurant.Name</h1>
<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>
<a asp-page="/Index">Home</a>

Pages/Restaurants/Edit.cshtml
@page "{id}"
@model EditModel
@{
    ViewData["Title"] = Model.Restaurant.Name;
}

<h1>Edit @Model.Restaurant.Name</h1>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>
    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine" asp-items="Model.CuisineTypes"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <input type="submit" name"save" value="Save" />
</form>
<div>
    <a asp-page="/Index">Home</a>
</div>

Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.min.js"
            asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.css"
            asp-fallback-test-class="sr-only"
            asp-fallback-test-property="position"
            asp-fallback-test-value="absolute" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OdeToFood</a>
            </div>
            <div class="navbar-right">
                <vc:login-logout></vc:login-logout>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()

        <footer>
            @RenderSection("footer", required: false)
        </footer>
    </div>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    </environment>

    <environment exclude="Development">
        <!-- <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-sdfa14fda312dfsa231rdfs">
        </script> -->
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
                asp-fallback-src="~/node_modules/jquery-validation/dist/jquery.validate.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
    </environment>
</body>
</html>

Pages/_Summary.cshtml
@model Restaurant

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cuisine: @Model.Cuisine
    </div>
    <div class="panel-footer">
        <a class="btn btn-default" asp-page="/Restaurants/Details" asp-route-id="@Model.Id">Details</a>
        <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>